// Same local shape the other shared helpers use (see lib/accountErrors.ts):
// strings.ts exports the values, not a type.
type Strings = Record<string, string>;

// ============================================================================
// Supabase Auth errors: raw error object -> translated, user-facing copy.
// ============================================================================
// screens/AuthScreen.tsx used to render `err.message` directly. On PRODUCTION,
// during the audit #8 acceptance test, that put Supabase's server-side English
// "Invalid login credentials" on the login card. An Arabic or French user gets
// that same English sentence: the string is generated by the auth server, which
// knows nothing about the app's locale.
//
// ---------------------------------------------------------------------------
// DO NOT render Supabase's `message`. Ever.
// ---------------------------------------------------------------------------
// Same whitelist discipline as lib/uploadErrors.ts and lib/accountErrors.ts:
// the raw input is used ONLY as a lookup key and cannot reach the return value.
// Anything unrecognised falls through to TRANSLATED generic copy.
// ---------------------------------------------------------------------------
//
// SCOPE: this helper covers the two calls AuthScreen makes, signInWithPassword
// and signUp. resetPasswordForEmail and updateUser already route through their
// own catalog strings (AuthScreen.handleForgotPassword, ResetPasswordScreen)
// and are deliberately left alone.
//
// ---------------------------------------------------------------------------
// authGenericError is a CLAIM, not a default.
// ---------------------------------------------------------------------------
// It reads "Invalid email or password". That is the correct copy for exactly
// one code, invalid_credentials. It must NEVER be the fallback: routing a 500,
// a ban or a timeout into it tells a user their password is wrong when it is
// not, which is a worse failure than the English leak it replaced. The generic
// tail is authUnexpectedError, which claims nothing.
// ---------------------------------------------------------------------------

/**
 * Codes that earn their own copy, keyed EXACTLY as @supabase/auth-js spells
 * them (lowercase snake_case, see its ErrorCode union in
 * node_modules/@supabase/auth-js/dist/main/lib/error-codes.d.ts) so this table
 * can be diffed against that union by eye.
 *
 * Everything absent here is deliberate. The not-actionable bucket
 * (user_banned, unexpected_failure, request_timeout, validation_failed,
 * signup_disabled, email_provider_disabled, bad_json, conflict) gets NO key:
 * there is no action to offer the user, exactly as accountErrors.ts argues for
 * its own unmapped shapes.
 *
 * user_already_exists / email_exists are excluded on SECURITY grounds, not by
 * oversight. A distinct "that email is already registered" message turns the
 * signup form into an account-enumeration oracle. It is the same leak
 * AuthScreen.handleForgotPassword already refuses to open with its conditional
 * "if an account exists" wording. Supabase additionally obfuscates this case
 * when email confirmation is on, so the code is unlikely to arrive at all.
 */
const CODE_TO_KEY: Record<string, string> = {
  // Wrong email or wrong password. THE case seen on production. Reuses the
  // existing catalog string, which already says exactly this in all three
  // locales.
  invalid_credentials: 'authGenericError',
  // Signed up but never clicked the confirmation link. Must stay distinct:
  // collapsed into "invalid email or password" the user retypes a CORRECT
  // password forever and never learns the link is waiting for them.
  email_not_confirmed: 'authEmailNotConfirmed',
  // Signup password below the project's configured minimum. AuthScreen does no
  // client-side length check, so this is genuinely reachable.
  weak_password: 'authWeakPassword',
  // Both rate-limit shapes say the same thing to the user: stop and wait.
  // Distinct from forgotPasswordRateLimited, whose copy is reset-link specific.
  over_request_rate_limit: 'authTooManyAttempts',
  over_email_send_rate_limit: 'authTooManyAttempts',
};

/**
 * HTTP status 0 means NO response was obtained.
 *
 * auth-js sets it in exactly two places, both in lib/fetch.js: when `fetch`
 * itself rejects (line 106, "network or CORS error") and when the thrown value
 * is not a Response at all (line 20). A real HTTP failure always carries its
 * real status.
 *
 * This is why the check is `status === 0` and NOT `isAuthRetryableFetchError`
 * or `code === undefined`:
 *   - AuthRetryableFetchError is ALSO thrown for 502/503/504 (fetch.js:16,24),
 *     which are SERVER outages. Telling a user with a working connection to
 *     "check your internet" would be wrong, so those fall to the generic.
 *   - `code === undefined` is true for every CustomAuthError subclass
 *     (AuthSessionMissingError, AuthInvalidTokenResponseError, ...), none of
 *     which are network failures.
 * Status 0 is the only signal that actually means "the request never landed".
 */
const NO_RESPONSE_STATUS = 0;

/** Supabase's own rate-limit status, matched even when no code accompanies it. */
const RATE_LIMITED_STATUS = 429;

/**
 * Read a property off an unknown thrown value without assuming its shape.
 *
 * The argument is `unknown` because a catch block can receive literally
 * anything: an AuthError, a TypeError, a string, null. Nothing read here is
 * ever returned to the caller; these values only ever become lookup keys.
 */
const read = (error: unknown, field: 'code' | 'status'): unknown =>
  typeof error === 'object' && error !== null && field in error
    ? (error as Record<string, unknown>)[field]
    : undefined;

/**
 * Translate a Supabase Auth error into user-facing copy.
 *
 * Unknown input (an unmapped code, a future enum, Supabase's English prose, a
 * plain TypeError, a string, null) falls back to TRANSLATED generic copy. The
 * return value is ALWAYS a catalog value: the input is read only to compute a
 * lookup key and has no path to the return.
 */
export const translateAuthError = (error: unknown, s: Strings): string => {
  const rawCode = read(error, 'code');
  const code = typeof rawCode === 'string' ? rawCode.trim().toLowerCase() : undefined;
  const rawStatus = read(error, 'status');
  const status = typeof rawStatus === 'number' ? rawStatus : undefined;

  // Most specific signal first: an explicit code. Then the two status-only
  // shapes, which arrive with no code at all.
  let key = code ? CODE_TO_KEY[code] : undefined;
  if (!key && status === NO_RESPONSE_STATUS) key = 'authNetworkError';
  if (!key && status === RATE_LIMITED_STATUS) key = 'authTooManyAttempts';

  const translated = key ? s[key] : undefined;
  return typeof translated === 'string' && translated ? translated : s.authUnexpectedError;
};
