import React from 'react';
import { ChevronRight, FileText } from 'lucide-react';
import { EmptyState } from './EmptyState';
import { useStrings } from '../i18n/useStrings';
import { useLanguage } from '../i18n/LanguageContext';
import { DESKTOP_COLUMNS, getPrimaryFields } from '../lib/searchResultCard';

type ResultTableProps = {
  data: any[];
  emptyStateComponent?: React.ReactNode;
  onRowClick?: (row: any) => void;
};

// Responsive results table restyled onto the --sa-* tokens.
//  - Desktop (>= md): SIX NAMED COLUMNS from DESKTOP_COLUMNS, each header read
//    from the i18n catalog. It used to render `Object.keys(data[0])` under
//    headers generated by a camelCase regex, which had three consequences, all
//    fixed here: every header was untranslated English in every locale
//    ("original File Name"); raw values reached cells untranslated, so status
//    rendered as "COMPLETED"; and the column SET was decided by row 1, so a
//    sparse first row deleted columns for every row beneath it. It also dragged
//    in `summary`, `rawText`, `detectedLanguage` and `documentSubtype`.
//  - Mobile (< md): PROGRESSIVE DISCLOSURE. Each row is a slim card showing only
//    the primary fields (name, vendor, amount, translated status) rather than
//    every column; the whole card taps through to the document detail route where
//    the full record already lives. The long file name truncates with an ellipsis
//    (never overflows or wraps one character per line).
// Both layouts now read from the SAME extractor (getPrimaryFields) and differ
// only in which of its fields they display — see the superset note in
// lib/searchResultCard.ts.
// Alignment is by logical `start` (dir="auto" on desktop values, dir="ltr" on the
// mobile amount) so Arabic mirrors correctly while numerals stay LTR. Rows stay
// clickable (read-only navigation to the document) in both layouts.
export const ResultTable = ({ data, emptyStateComponent, onRowClick }: ResultTableProps) => {
  const s = useStrings();
  const { language } = useLanguage();

  if (!data || data.length === 0) {
    return (emptyStateComponent || <EmptyState message={s.noData} />) as any;
  }

  const isClickable = typeof onRowClick === 'function';

  // Shared muted placeholder for a genuinely empty value.
  // The glyph is U+002D HYPHEN-MINUS, deliberately: the catalog guards reject
  // U+2014 and U+2013 (dashboardRestyle.test.tsx:141-142), and a truly empty
  // cell is ambiguous — a reader cannot tell "no vendor on this document" from
  // "this row failed to load".
  // The accessible name is an sr-only span, NOT an aria-label on the glyph.
  // aria-label on a role-less <span> is not reliably exposed, so the previous
  // spelling announced as "hyphen" or as nothing at all.
  const placeholder = (
    <>
      <span className="text-ink-fainter" aria-hidden="true">-</span>
      <span className="sr-only">{s.notAvailable}</span>
    </>
  );

  return (
    <>
      {/* ── Desktop: horizontal table (>= md) ─────────────────────────────── */}
      <div className="hidden overflow-x-auto md:block">
        <table className="w-full border-collapse text-start">
          <thead>
            <tr className="border-b border-divider bg-surface-alt">
              {DESKTOP_COLUMNS.map((c) => (
                <th
                  key={c.field}
                  className="px-5 py-3.5 text-start text-label font-semibold uppercase tracking-wide text-ink-tertiary"
                >
                  {(s as any)[c.labelKey]}
                </th>
              ))}
              {isClickable && <th className="w-10 px-5 py-3.5" aria-hidden="true" />}
            </tr>
          </thead>
          <tbody>
            {data.map((row, i) => {
              const fields = getPrimaryFields(row, s as any, language);
              return (
              <tr
                key={row.id ?? i}
                onClick={isClickable ? () => onRowClick!(row) : undefined}
                className={`group border-b border-divider transition-colors last:border-b-0 ${
                  isClickable ? 'cursor-pointer hover:bg-surface-alt' : ''
                }`}
              >
                {DESKTOP_COLUMNS.map((c) => {
                  // `status` is the one field that is an object rather than a
                  // string: it carries the TRANSLATED label plus its dot tokens.
                  // Reading .label here is what stops the raw "COMPLETED" enum
                  // reaching a desktop cell, which is what it used to do.
                  const v = c.field === 'status' ? fields.status?.label ?? null : (fields as any)[c.field];
                  return (
                    <td
                      key={c.field}
                      className="px-5 py-3.5 text-start align-top text-sm text-ink-secondary transition-colors group-hover:text-ink"
                    >
                      {v == null || v === '' ? placeholder : <span dir="auto">{v}</span>}
                    </td>
                  );
                })}
                {isClickable && (
                  <td className="px-5 py-3.5 text-end align-top text-ink-fainter">
                    <ChevronRight size={16} className="inline rtl:-scale-x-100" />
                  </td>
                )}
              </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* ── Mobile: slim primary-field cards (< md) ───────────────────────── */}
      <div className="flex flex-col gap-3 md:hidden">
        {data.map((row, i) => {
          const { title, vendor, amount, status } = getPrimaryFields(row, s as any, language);
          const CardTag = isClickable ? 'button' : 'div';
          return (
            <CardTag
              key={row.id ?? i}
              type={isClickable ? 'button' : undefined}
              onClick={isClickable ? () => onRowClick!(row) : undefined}
              className={`flex w-full flex-col gap-3 rounded-card border border-line bg-surface-raised p-4 text-start shadow-card transition-colors ${
                isClickable ? 'cursor-pointer active:bg-surface-alt' : ''
              }`}
            >
              <div className="flex items-start gap-3">
                <span className="flex h-9 w-9 flex-shrink-0 items-center justify-center rounded-btn border border-line bg-surface text-ink-faint">
                  <FileText size={16} />
                </span>
                <div className="min-w-0 flex-1">
                  {/* dir="auto" on the truncating box: without it the box inherits
                      the page direction, so in Arabic a Latin filename/vendor
                      truncates from its leading (identifying) end. */}
                  <div className="truncate text-sm font-semibold text-ink" dir="auto">{title}</div>
                  {vendor && <div className="mt-0.5 truncate text-xs text-ink-muted" dir="auto">{vendor}</div>}
                </div>
                {amount && (
                  <span className="flex-shrink-0 text-sm font-semibold text-ink" dir="ltr">
                    {amount}
                  </span>
                )}
              </div>

              {(status || isClickable) && (
                <div className="flex items-center justify-between border-t border-divider pt-3">
                  {status ? (
                    <span className="inline-flex min-w-0 items-center gap-2">
                      <span className={`h-1.5 w-1.5 flex-shrink-0 rounded-pill ${status.dot}`} />
                      <span className={`truncate text-xs font-medium ${status.text}`}>{status.label}</span>
                    </span>
                  ) : (
                    <span />
                  )}
                  {isClickable && (
                    <ChevronRight size={16} className="flex-shrink-0 text-ink-fainter rtl:-scale-x-100" />
                  )}
                </div>
              )}
            </CardTag>
          );
        })}
      </div>
    </>
  );
};
