import React from 'react';
import { ChevronRight, FileText } from 'lucide-react';
import { EmptyState } from './EmptyState';
import { useStrings } from '../i18n/useStrings';
import { useLanguage } from '../i18n/LanguageContext';
import { DESKTOP_COLUMNS, getPrimaryFields } from '../lib/searchResultCard';

type ResultTableProps = {
  data: any[];
  emptyStateComponent?: React.ReactNode;
  onRowClick?: (row: any) => void;
};

// Responsive results table restyled onto the --sa-* tokens.
//  - Desktop (>= md): SIX NAMED COLUMNS from DESKTOP_COLUMNS, each header read
//    from the i18n catalog. It used to render `Object.keys(data[0])` under
//    headers generated by a camelCase regex, which had three consequences, all
//    fixed here: every header was untranslated English in every locale
//    ("original File Name"); raw values reached cells untranslated, so status
//    rendered as "COMPLETED"; and the column SET was decided by row 1, so a
//    sparse first row deleted columns for every row beneath it. It also dragged
//    in `summary`, `rawText`, `detectedLanguage` and `documentSubtype`.
//    The two free-text columns (Name, Vendor) are BOUNDED and clip with an
//    ellipsis; the other four are formatted to a bounded length and are not.
//    See the direction note on the bounded cell below before changing it.
//  - Mobile (< md): PROGRESSIVE DISCLOSURE. Each row is a slim card showing only
//    the primary fields (name, vendor, amount, translated status) rather than
//    every column; the whole card taps through to the document detail route where
//    the full record already lives. The long file name truncates with an ellipsis
//    (never overflows or wraps one character per line).
// Both layouts now read from the SAME extractor (getPrimaryFields) and differ
// only in which of its fields they display — see the superset note in
// lib/searchResultCard.ts.
// Alignment is by logical `start` (dir="auto" on desktop values, dir="ltr" on the
// mobile amount) so Arabic mirrors correctly while numerals stay LTR. Rows stay
// clickable (read-only navigation to the document) in both layouts.
export const ResultTable = ({ data, emptyStateComponent, onRowClick }: ResultTableProps) => {
  const s = useStrings();
  const { language } = useLanguage();

  if (!data || data.length === 0) {
    return (emptyStateComponent || <EmptyState message={s.noData} />) as any;
  }

  const isClickable = typeof onRowClick === 'function';

  // Shared muted placeholder for a genuinely empty value.
  // The glyph is U+002D HYPHEN-MINUS, deliberately: the catalog guards reject
  // U+2014 and U+2013 (dashboardRestyle.test.tsx:141-142), and a truly empty
  // cell is ambiguous — a reader cannot tell "no vendor on this document" from
  // "this row failed to load".
  // The accessible name is an sr-only span, NOT an aria-label on the glyph.
  // aria-label on a role-less <span> is not reliably exposed, so the previous
  // spelling announced as "hyphen" or as nothing at all.
  const placeholder = (
    <>
      <span className="text-ink-fainter" aria-hidden="true">-</span>
      <span className="sr-only">{s.notAvailable}</span>
    </>
  );

  return (
    <>
      {/* ── Desktop: horizontal table (>= md) ─────────────────────────────── */}
      <div className="hidden overflow-x-auto md:block">
        <table className="w-full border-collapse text-start">
          <thead>
            <tr className="border-b border-divider bg-surface-alt">
              {DESKTOP_COLUMNS.map((c) => (
                <th
                  key={c.field}
                  className="px-5 py-3.5 text-start text-label font-semibold uppercase tracking-wide text-ink-tertiary"
                >
                  {(s as any)[c.labelKey]}
                </th>
              ))}
              {isClickable && <th className="w-10 px-5 py-3.5" aria-hidden="true" />}
            </tr>
          </thead>
          <tbody>
            {data.map((row, i) => {
              const fields = getPrimaryFields(row, s as any, language);
              return (
              <tr
                key={row.id ?? i}
                onClick={isClickable ? () => onRowClick!(row) : undefined}
                className={`group border-b border-divider transition-colors last:border-b-0 ${
                  isClickable ? 'cursor-pointer hover:bg-surface-alt' : ''
                }`}
              >
                {DESKTOP_COLUMNS.map((c) => {
                  // `status` is the one field that is an object rather than a
                  // string: it carries the TRANSLATED label plus its dot tokens.
                  // Reading .label here is what stops the raw "COMPLETED" enum
                  // reaching a desktop cell, which is what it used to do.
                  const v = c.field === 'status' ? fields.status?.label ?? null : (fields as any)[c.field];
                  return (
                    <td
                      key={c.field}
                      className="px-5 py-3.5 text-start align-top text-sm text-ink-secondary transition-colors group-hover:text-ink"
                    >
                      {v == null || v === '' ? (
                        placeholder
                      ) : c.maxCh ? (
                        // ── The bounded cell (defect D1) ─────────────────────
                        // Only Name and Vendor take this branch; see the maxCh
                        // note in lib/searchResultCard.ts for why the other four
                        // are not bounded. Without it a single unbreakable token
                        // — `JPEG_20260615_222241_1286235000237534355.jpg`, where
                        // underscores are not break opportunities — sets the
                        // column's minimum width and pushes the table past its
                        // container into a horizontal scroll.
                        //
                        // A <div>, not the existing <span>: `overflow` and
                        // `text-overflow` do not apply to a non-replaced inline
                        // box, so a span could not clip at all. And not the <td>
                        // either: under `table-layout: auto` a cell's max-width
                        // is advisory and the algorithm may exceed it, whereas a
                        // block child's max-width caps its own box and the cell
                        // takes its preferred width from that child.
                        //
                        // DIRECTION: dir="auto", DECIDED, not inherited.
                        // This box holds user data inside a page whose direction
                        // is the UI language's, and those are independent — so
                        // the ambient direction is never the right answer here,
                        // only the unconsidered one (#142). Three values were
                        // available and only one is correct for BOTH scripts:
                        //   inherit  in Arabic the box resolves RTL, and a Latin
                        //            filename loses its LEADING end — the reader
                        //            gets a wrong string, not a missing one.
                        //   dir=ltr  correct for a Latin name, and wrong for an
                        //            Arabic one, which then loses its leading end
                        //            instead. Arabic filenames are a real case
                        //            here, measured in Chrome and recorded at
                        //            tests/rtlTruncation.test.ts:17.
                        //   dir=auto takes the direction from the value's own
                        //            first strong character, so the HEAD survives
                        //            in both. This is the behaviour Abo Jad
                        //            confirmed on the Arabic activity screen —
                        //            head kept, tail eaten — which is the same
                        //            idiom at ActivityScreen.tsx:114, so this
                        //            matches an observed-good result rather than
                        //            inventing a preference.
                        // A second, independent reason it must be `auto` and not
                        // a guess about the script: `title` is not necessarily a
                        // filename. getPrimaryFields falls back through `name`,
                        // `entity.canonicalName` and firstReadable(), so the
                        // value's script is genuinely unknown at this line.
                        //
                        // WHY THE APP-WIDE GUARD CANNOT ENFORCE THIS BOX, in case
                        // someone later deletes the dir and finds every check
                        // still green. tests/rtlTruncation.test.ts DOES scan this
                        // element — unlike the Sidebar box, it truncates by class
                        // — but its Class-B rule fires only when the element's
                        // content names `fileName`, `originalFileName` or
                        // `email`. This is a generic cell renderer: the content is
                        // `{v}`, so the rule looks straight at it and clears it.
                        // Measured, not assumed: with the dir deleted from this
                        // box, rtlTruncation.test.ts stays fully green and only
                        // guard 12 goes red. Adding `v` to that allowlist is not
                        // available — it would fire on every truncating box in
                        // the app. So this is guarded where that file says such
                        // cases belong: per screen, at the DOM level, by a human
                        // who decided which it is — searchTableColumns.test.tsx,
                        // guard 12. The mobile card two branches below is blind
                        // for the same reason (`{title}`, `{vendor}`).
                        //
                        // `title` IS A POINTER AFFORDANCE, NOT AN ACCESSIBILITY
                        // MEASURE, and must not be mistaken for one. The clipping
                        // is CSS: the full string stays in the text node, so a
                        // screen reader reads the whole name whether or not it is
                        // visually clipped, and nothing needs recovering for AT.
                        // On this role-less <div> the title is exactly the shape
                        // that failed for the placeholder's old aria-label — not
                        // reliably exposed as an accessible name — which costs
                        // nothing only because AT never needed it. Guard 12
                        // asserts the cell's text is still the complete value,
                        // which is the claim that actually protects AT. Keyboard
                        // users, who cannot hover, reach the full name by
                        // activating the row.
                        <div
                          className="truncate"
                          dir={c.dir ?? 'auto'}
                          title={v}
                          style={{ maxWidth: `${c.maxCh}ch` }}
                        >
                          {v}
                        </div>
                      ) : (
                        // ── The direction-pinned cell (defect F2) ────────────
                        // `c.dir ?? 'auto'`, not a literal `auto`. Only `amount`
                        // declares a direction, and the reasoning — the Intl
                        // code points, the measured comparison, and why an
                        // isolate element here would NOT fix it — sits beside
                        // the declaration in lib/searchResultCard.ts.
                        //
                        // Do not wrap this value in an isolate element. That
                        // element's direction is `auto` by definition, so it
                        // re-runs the detection this line exists to override,
                        // finds the leading RLM, and puts the `$` back on the
                        // wrong side. Measured, and guard 13 asserts its
                        // absence. The span needs no isolate of its own —
                        // `[dir]` already computes `unicode-bidi: isolate`.
                        //
                        // The same `c.dir ?? 'auto'` is on the bounded branch
                        // above so the two branches cannot drift, not because a
                        // bounded column pins its direction — none does, and
                        // `title`/`vendor` must keep `auto` (screenshot 9c).
                        <span dir={c.dir ?? 'auto'}>{v}</span>
                      )}
                    </td>
                  );
                })}
                {isClickable && (
                  <td className="px-5 py-3.5 text-end align-top text-ink-fainter">
                    <ChevronRight size={16} className="inline rtl:-scale-x-100" />
                  </td>
                )}
              </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* ── Mobile: slim primary-field cards (< md) ───────────────────────── */}
      <div className="flex flex-col gap-3 md:hidden">
        {data.map((row, i) => {
          const { title, vendor, amount, status } = getPrimaryFields(row, s as any, language);
          const CardTag = isClickable ? 'button' : 'div';
          return (
            <CardTag
              key={row.id ?? i}
              type={isClickable ? 'button' : undefined}
              onClick={isClickable ? () => onRowClick!(row) : undefined}
              className={`flex w-full flex-col gap-3 rounded-card border border-line bg-surface-raised p-4 text-start shadow-card transition-colors ${
                isClickable ? 'cursor-pointer active:bg-surface-alt' : ''
              }`}
            >
              <div className="flex items-start gap-3">
                <span className="flex h-9 w-9 flex-shrink-0 items-center justify-center rounded-btn border border-line bg-surface text-ink-faint">
                  <FileText size={16} />
                </span>
                <div className="min-w-0 flex-1">
                  {/* dir="auto" on the truncating box: without it the box inherits
                      the page direction, so in Arabic a Latin filename/vendor
                      truncates from its leading (identifying) end. */}
                  <div className="truncate text-sm font-semibold text-ink" dir="auto">{title}</div>
                  {vendor && <div className="mt-0.5 truncate text-xs text-ink-muted" dir="auto">{vendor}</div>}
                </div>
                {amount && (
                  <span className="flex-shrink-0 text-sm font-semibold text-ink" dir="ltr">
                    {amount}
                  </span>
                )}
              </div>

              {(status || isClickable) && (
                <div className="flex items-center justify-between border-t border-divider pt-3">
                  {status ? (
                    <span className="inline-flex min-w-0 items-center gap-2">
                      <span className={`h-1.5 w-1.5 flex-shrink-0 rounded-pill ${status.dot}`} />
                      <span className={`truncate text-xs font-medium ${status.text}`}>{status.label}</span>
                    </span>
                  ) : (
                    <span />
                  )}
                  {isClickable && (
                    <ChevronRight size={16} className="flex-shrink-0 text-ink-fainter rtl:-scale-x-100" />
                  )}
                </div>
              )}
            </CardTag>
          );
        })}
      </div>
    </>
  );
};
